//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRegistryTechingClass {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AppSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSetting defaultInstance = ((AppSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSetting())));
        
        public static AppSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tinhanh89@gmail.com,ngocbmt94@gmail.com,phanthituuyenkt@gmail.com")]
        public string ReceivedEmails {
            get {
                return ((string)(this["ReceivedEmails"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tannguyent140489@gmail.com")]
        public string SenderEmail {
            get {
                return ((string)(this["SenderEmail"]));
            }
            set {
                this["SenderEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@tinhanh89")]
        public string PassSenderEmail {
            get {
                return ((string)(this["PassSenderEmail"]));
            }
            set {
                this["PassSenderEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tannguyent140489@gmail.com")]
        public string SenderUser {
            get {
                return ((string)(this["SenderUser"]));
            }
            set {
                this["SenderUser"] = value;
            }
        }
    }
}
